# Generated by Django 5.0.2 on 2024-02-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
