# Generated by Django 5.0.3 on 2024-03-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whistleblower_site', '0002_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('follow_up', models.BooleanField()),
                ('publish', models.BooleanField()),
                ('anonymous', models.BooleanField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='org-report-uploaded-files/')),
            ],
        ),
    ]
