# Generated by Django 5.0.3 on 2024-03-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower_site', '0004_user_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='anonymous',
            new_name='remain_anonymous',
        ),
        migrations.AddField(
            model_name='report',
            name='anonymous_account',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
