# Generated by Django 5.0.2 on 2024-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower_site', '0005_rename_anonymous_report_remain_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
