# Generated by Django 5.0.3 on 2024-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whistleblower_site', '0006_report_admin_notes_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='report',
            name='remain_anonymous',
        ),
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
